/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    'service-variants': ServiceVariant;
    slots: Slot;
    'slot-templates': SlotTemplate;
    bookings: Booking;
    payments: Payment;
    notifications: Notification;
    'membership-cards': MembershipCard;
    'loyalty-transactions': LoyaltyTransaction;
    vouchers: Voucher;
    'referral-logs': ReferralLog;
    reviews: Review;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-variants': ServiceVariantsSelect<false> | ServiceVariantsSelect<true>;
    slots: SlotsSelect<false> | SlotsSelect<true>;
    'slot-templates': SlotTemplatesSelect<false> | SlotTemplatesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'membership-cards': MembershipCardsSelect<false> | MembershipCardsSelect<true>;
    'loyalty-transactions': LoyaltyTransactionsSelect<false> | LoyaltyTransactionsSelect<true>;
    vouchers: VouchersSelect<false> | VouchersSelect<true>;
    'referral-logs': ReferralLogsSelect<false> | ReferralLogsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'booking-settings': BookingSetting;
    'membership-tiers': MembershipTier;
  };
  globalsSelect: {
    'booking-settings': BookingSettingsSelect<false> | BookingSettingsSelect<true>;
    'membership-tiers': MembershipTiersSelect<false> | MembershipTiersSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullName: string;
  /**
   * Pakistani format without + prefix e.g. 923001234567
   */
  mobileNumber?: string | null;
  /**
   * Auto-set to mobileNumber on create if blank
   */
  whatsappNumber?: string | null;
  /**
   * Auto-generated REF-XXXXX
   */
  referralCode?: string | null;
  /**
   * Set at signup when referral code is used
   */
  referredBy?: (number | null) | User;
  loyaltyPointsBalance?: number | null;
  currentTier?: ('Beginner' | 'Gold' | 'Platinum') | null;
  isActive?: boolean | null;
  role: 'customer' | 'admin';
  otp?: string | null;
  otpExpiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  serviceName: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Inactive services are hidden in the booking wizard
   */
  isActive?: boolean | null;
  /**
   * Base points before tier multiplier is applied
   */
  loyaltyPointsAwarded: number;
  steps?:
    | {
        stepName: 'Exterior' | 'Engine' | 'Interior';
        stepDescription?: string | null;
        stepOrder: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-variants".
 */
export interface ServiceVariant {
  id: number;
  service: number | Service;
  carType: 'Hatchback' | 'Sedan' | 'Luxury Sedan' | 'Crossover / MPV' | '7-Seater SUV' | 'Luxury SUV / Exotic';
  location: 'Studio' | 'Doorstep';
  /**
   * Price in PKR
   */
  price: number;
  durationMinutes: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slots".
 */
export interface Slot {
  id: number;
  date: string;
  /**
   * HH:MM format e.g. 09:00
   */
  startTime: string;
  /**
   * HH:MM format. Auto-computed from startTime + duration when using slot templates
   */
  endTime: string;
  /**
   * Auto-computed from date on save
   */
  dayOfWeek?: ('Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri' | 'Sat' | 'Sun') | null;
  /**
   * Set false automatically when currentBookingCount reaches maxBookings
   */
  isAvailable?: boolean | null;
  /**
   * Manual override — blocks this slot regardless of booking count
   */
  isBlockedByAdmin?: boolean | null;
  maxBookings?: number | null;
  /**
   * Managed automatically by the bookings system
   */
  currentBookingCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slot-templates".
 */
export interface SlotTemplate {
  id: number;
  dayOfWeek: 'Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri' | 'Sat' | 'Sun';
  /**
   * HH:MM format e.g. 09:00
   */
  startTime: string;
  /**
   * HH:MM format e.g. 18:00
   */
  endTime: string;
  /**
   * Duration of each generated slot in minutes
   */
  slotIntervalMinutes?: number | null;
  /**
   * Only active templates trigger slot generation on save
   */
  isActive?: boolean | null;
  /**
   * Slots will be generated from today up to and including this date
   */
  generateUntilDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  /**
   * Auto-generated BK-XXXXX
   */
  bookingReference?: string | null;
  user: number | User;
  service: number | Service;
  serviceVariant: number | ServiceVariant;
  slot: number | Slot;
  carModel: string;
  carYear: string;
  carColor: string;
  location: 'Studio' | 'Doorstep';
  /**
   * Required when location is Doorstep
   */
  doorstepAddress?: string | null;
  status: 'Pending' | 'Approved' | 'Cancelled' | 'Completed';
  cancellationRequestedBy?: ('user' | 'admin') | null;
  cancellationReason?: string | null;
  voucherApplied?: (number | null) | Voucher;
  /**
   * Base price from service variant before any discount
   */
  originalPrice?: number | null;
  /**
   * Amount discounted via voucher
   */
  discountAmount?: number | null;
  /**
   * Computed: originalPrice minus discountAmount
   */
  finalPrice?: number | null;
  loyaltyPointsEarned?: number | null;
  payment?: (number | null) | Payment;
  whatsappAlertSent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vouchers".
 */
export interface Voucher {
  id: number;
  /**
   * Auto-generated VC-XXXXXXXX
   */
  code?: string | null;
  assignedToUser: number | User;
  /**
   * Discount percentage applied at checkout
   */
  discountPercent?: number | null;
  validUntil: string;
  isUsed?: boolean | null;
  /**
   * Timestamp of redemption
   */
  usedAt?: string | null;
  source?: 'Referral' | null;
  /**
   * The booking that triggered this referral reward
   */
  referralBooking?: (number | null) | Booking;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  booking: number | Booking;
  method: 'Bank Transfer' | 'Online';
  /**
   * Amount in PKR
   */
  amount: number;
  status: 'Pending' | 'Confirmed' | 'Failed';
  /**
   * Entered by the customer
   */
  bankTransferReferenceNumber?: string | null;
  /**
   * Customer uploads payment receipt
   */
  bankTransferReceiptImage?: (number | null) | Media;
  /**
   * Admin user who confirmed the payment
   */
  confirmedByAdmin?: (number | null) | User;
  confirmedAt?: string | null;
  /**
   * Future: online payment gateway reference
   */
  gatewayReference?: string | null;
  /**
   * Future: raw gateway response payload
   */
  gatewayResponse?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user?: (number | null) | User;
  type:
    | 'OTP'
    | 'Booking Confirmed'
    | 'Booking Cancelled'
    | 'Payment Confirmed'
    | 'Reminder'
    | 'Tier Upgrade'
    | 'Free Slot Unlocked'
    | 'Referral Reward'
    | 'Review Thanks'
    | 'Cancellation Request Alert';
  channel: 'WhatsApp' | 'Email';
  messageBody?: string | null;
  status?: ('Sent' | 'Failed') | null;
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-cards".
 */
export interface MembershipCard {
  id: number;
  /**
   * One membership card per customer
   */
  user: number | User;
  currentTier?: ('Beginner' | 'Gold' | 'Platinum') | null;
  /**
   * Resets to 0 when a free slot is granted
   */
  servicesCompletedInCycle?: number | null;
  /**
   * Set true when cycle threshold is reached
   */
  freeSlotUnlocked?: boolean | null;
  /**
   * Cleared after the free booking is consumed
   */
  freeSlotUsed?: boolean | null;
  /**
   * Date the current loyalty cycle began
   */
  cycleStartDate?: string | null;
  /**
   * Cumulative all-time completed service count
   */
  totalServicesEver?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loyalty-transactions".
 */
export interface LoyaltyTransaction {
  id: number;
  user: number | User;
  booking: number | Booking;
  /**
   * Final points after multiplier applied
   */
  pointsEarned: number;
  tierMultiplierApplied: number;
  transactionDate: string;
  /**
   * Optional admin note
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referral-logs".
 */
export interface ReferralLog {
  id: number;
  /**
   * The customer who shared their referral code
   */
  referrer: number | User;
  /**
   * The new customer who signed up using the referral code
   */
  referredUser: number | User;
  /**
   * Set when the referral reward is triggered
   */
  referredUserFirstBooking?: (number | null) | Booking;
  /**
   * The reward voucher created for the referrer
   */
  voucherIssued?: (number | null) | Voucher;
  status?: ('Pending' | 'Rewarded') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * One review per booking
   */
  booking: number | Booking;
  user: number | User;
  /**
   * Auto-generated e.g. SVC-4829-XK. Generated via /api/reviews/generate-token
   */
  reviewToken?: string | null;
  /**
   * Set when the token is generated
   */
  tokenExpiresAt?: string | null;
  /**
   * Set true on submission — single-use token
   */
  tokenUsed?: boolean | null;
  /**
   * Admin must upload a car photo before generating the review token
   */
  carPhotoByAdmin?: (number | null) | Media;
  rating?: number | null;
  reviewText?: string | null;
  customerExtraImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  submittedAt?: string | null;
  /**
   * Auto-set true on submission
   */
  isVerified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'service-variants';
        value: number | ServiceVariant;
      } | null)
    | ({
        relationTo: 'slots';
        value: number | Slot;
      } | null)
    | ({
        relationTo: 'slot-templates';
        value: number | SlotTemplate;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'membership-cards';
        value: number | MembershipCard;
      } | null)
    | ({
        relationTo: 'loyalty-transactions';
        value: number | LoyaltyTransaction;
      } | null)
    | ({
        relationTo: 'vouchers';
        value: number | Voucher;
      } | null)
    | ({
        relationTo: 'referral-logs';
        value: number | ReferralLog;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  mobileNumber?: T;
  whatsappNumber?: T;
  referralCode?: T;
  referredBy?: T;
  loyaltyPointsBalance?: T;
  currentTier?: T;
  isActive?: T;
  role?: T;
  otp?: T;
  otpExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  serviceName?: T;
  description?: T;
  isActive?: T;
  loyaltyPointsAwarded?: T;
  steps?:
    | T
    | {
        stepName?: T;
        stepDescription?: T;
        stepOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-variants_select".
 */
export interface ServiceVariantsSelect<T extends boolean = true> {
  service?: T;
  carType?: T;
  location?: T;
  price?: T;
  durationMinutes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slots_select".
 */
export interface SlotsSelect<T extends boolean = true> {
  date?: T;
  startTime?: T;
  endTime?: T;
  dayOfWeek?: T;
  isAvailable?: T;
  isBlockedByAdmin?: T;
  maxBookings?: T;
  currentBookingCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slot-templates_select".
 */
export interface SlotTemplatesSelect<T extends boolean = true> {
  dayOfWeek?: T;
  startTime?: T;
  endTime?: T;
  slotIntervalMinutes?: T;
  isActive?: T;
  generateUntilDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  bookingReference?: T;
  user?: T;
  service?: T;
  serviceVariant?: T;
  slot?: T;
  carModel?: T;
  carYear?: T;
  carColor?: T;
  location?: T;
  doorstepAddress?: T;
  status?: T;
  cancellationRequestedBy?: T;
  cancellationReason?: T;
  voucherApplied?: T;
  originalPrice?: T;
  discountAmount?: T;
  finalPrice?: T;
  loyaltyPointsEarned?: T;
  payment?: T;
  whatsappAlertSent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  booking?: T;
  method?: T;
  amount?: T;
  status?: T;
  bankTransferReferenceNumber?: T;
  bankTransferReceiptImage?: T;
  confirmedByAdmin?: T;
  confirmedAt?: T;
  gatewayReference?: T;
  gatewayResponse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  channel?: T;
  messageBody?: T;
  status?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-cards_select".
 */
export interface MembershipCardsSelect<T extends boolean = true> {
  user?: T;
  currentTier?: T;
  servicesCompletedInCycle?: T;
  freeSlotUnlocked?: T;
  freeSlotUsed?: T;
  cycleStartDate?: T;
  totalServicesEver?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loyalty-transactions_select".
 */
export interface LoyaltyTransactionsSelect<T extends boolean = true> {
  user?: T;
  booking?: T;
  pointsEarned?: T;
  tierMultiplierApplied?: T;
  transactionDate?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vouchers_select".
 */
export interface VouchersSelect<T extends boolean = true> {
  code?: T;
  assignedToUser?: T;
  discountPercent?: T;
  validUntil?: T;
  isUsed?: T;
  usedAt?: T;
  source?: T;
  referralBooking?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referral-logs_select".
 */
export interface ReferralLogsSelect<T extends boolean = true> {
  referrer?: T;
  referredUser?: T;
  referredUserFirstBooking?: T;
  voucherIssued?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  booking?: T;
  user?: T;
  reviewToken?: T;
  tokenExpiresAt?: T;
  tokenUsed?: T;
  carPhotoByAdmin?: T;
  rating?: T;
  reviewText?: T;
  customerExtraImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  submittedAt?: T;
  isVerified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-settings".
 */
export interface BookingSetting {
  id: number;
  /**
   * Auto-approve bookings when a bank transfer payment is confirmed
   */
  autoApproveBankTransfer?: boolean | null;
  /**
   * Auto-approve bookings when an online payment is confirmed
   */
  autoApproveOnlinePayment?: boolean | null;
  /**
   * Discount % for referral reward vouchers
   */
  defaultReferralVoucherPercent?: number | null;
  /**
   * Days until a newly issued voucher expires
   */
  voucherExpiryDays?: number | null;
  /**
   * Default slot duration used by slot generator
   */
  slotIntervalMinutes?: number | null;
  /**
   * Hours before appointment to send WhatsApp reminder
   */
  reminderHoursBefore?: number | null;
  /**
   * Minutes until a review token expires (default 2880 = 48 hours)
   */
  reviewTokenExpiryMinutes?: number | null;
  loyaltyPointsMultipliers?: {
    beginnerMultiplier?: number | null;
    goldMultiplier?: number | null;
    platinumMultiplier?: number | null;
  };
  /**
   * Shown to customers at bank transfer checkout
   */
  bankAccountDetails?: {
    bankName?: string | null;
    accountTitle?: string | null;
    accountNumber?: string | null;
    /**
     * IBAN format e.g. PK36SCBL0000001123456702
     */
    iban?: string | null;
    /**
     * Additional payment instructions shown to customer
     */
    instructions?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-tiers".
 */
export interface MembershipTier {
  id: number;
  /**
   * Configure the three loyalty tiers. Do not reorder — order must be Beginner → Gold → Platinum.
   */
  tiers?:
    | {
        tierName: 'Beginner' | 'Gold' | 'Platinum';
        /**
         * Total completed services required to reach this tier. Use 0 for the default tier.
         */
        unlocksAtServiceCount: number;
        /**
         * Services completed in current cycle before a free slot is unlocked
         */
        freeSlotAtCycleCount: number;
        /**
         * Multiplier applied to base loyaltyPointsAwarded on each booking
         */
        pointsMultiplier: number;
        /**
         * Hex colour for UI badge e.g. #C0A020
         */
        badgeColor?: string | null;
        /**
         * Shown to customers on their dashboard
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-settings_select".
 */
export interface BookingSettingsSelect<T extends boolean = true> {
  autoApproveBankTransfer?: T;
  autoApproveOnlinePayment?: T;
  defaultReferralVoucherPercent?: T;
  voucherExpiryDays?: T;
  slotIntervalMinutes?: T;
  reminderHoursBefore?: T;
  reviewTokenExpiryMinutes?: T;
  loyaltyPointsMultipliers?:
    | T
    | {
        beginnerMultiplier?: T;
        goldMultiplier?: T;
        platinumMultiplier?: T;
      };
  bankAccountDetails?:
    | T
    | {
        bankName?: T;
        accountTitle?: T;
        accountNumber?: T;
        iban?: T;
        instructions?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-tiers_select".
 */
export interface MembershipTiersSelect<T extends boolean = true> {
  tiers?:
    | T
    | {
        tierName?: T;
        unlocksAtServiceCount?: T;
        freeSlotAtCycleCount?: T;
        pointsMultiplier?: T;
        badgeColor?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}